apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceSpec.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app:  {{ .Values.Labels.app }}
spec:
  selector:
    app: {{ .Values.Labels.app }}
  type: {{ .Values.serviceSpec.type }}
  ports:
  - name: {{ .Release.Name }}
{{- range  .Values.serviceSpec.ports }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetport }}
{{- end }}