
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avaloq-frontend
  namespace: argocd    # namespace where Argo CD is installed
spec:
  project: default

  source:
    repoURL: https://github.com/an618/avaloq-frontend.git  # your GitHub repo URL
    targetRevision: main                                  # branch or tag
    path: gbs-infra/avaloq-frontend                       # relative path to your Helm chart

  destination:
    server: https://kubernetes.default.svc
    namespace: gbs                                       # target namespace for deployment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
