apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avaloq-frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/an618/gbs-infra.git   # your actual repo URL
    targetRevision: master                             # your branch
    path: avaloq-frontend                             # relative path to your Helm chart inside the repo

  destination:
    server: https://kubernetes.default.svc
    namespace: gbs                                   # target namespace in your cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

